### ISSUE TITLE
--no_npy is ignored in new version

### ISSUE THREAD

**Issue by lacan** [MouseLand/cellpose#402]
The latest version with Omnipose ignores the --no_npy flag and will always out put an npy file

Tested on Windows 10, though I am sure that this is quite platform independent.

**Comment by dkurt** [comment]
must be fixed by https://github.com/MouseLand/cellpose/commit/45f1a3c640efb8ca7d252712620af6f58d024c55

**Comment by kevinjohncutler** [comment]
Yes I am pretty sure I fixed that a while ago, @lacan are you sure you have the latest version?

**Comment by tinevez** [comment]
I confirm that this issue still happens with Cellpose v0.7.2:

```sh
❯ ls -1
0.tif
0_cp_masks.png
0_cp_output.png
0_seg.npy
```

Command line:
```
/opt/anaconda3/envs/cellpose/bin/python -m cellpose --dir /var/folders/ff/v_0sfcb921n7n93dpjn4kft80000gq/T/TrackMate-Cellpose_7866146421345396763 --chan 2 --chan2 1 --diameter 47.33766000000001 --pretrained_model cyto --save_png --no_npy
```

Cellpose version:

```
❯ conda list
# packages in environment at /opt/anaconda3/envs/cellpose:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.10.26           hecd8cb5_2  
cachetools                4.2.4                    pypi_0    pypi
cellpose                  0.7.2                    pypi_0    pypi
```

**Comment by kevinjohncutler** [comment]
@tinevez thanks for confirming that, but the latest version is 0.7.3, which fixed this issue on Nov. 19.

**Comment by tinevez** [comment]
My bad sorry. Thank you so much!
