### ISSUE TITLE
[INSTALL]ERROR: Could not build wheels for imagecodecs, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by austinnn7** [MouseLand/cellpose#742]
**Install problem**
**ERROR: Could not build wheels for imagecodecs, which is required to install pyproject.toml-based projects**

**Environment info**
# Name                    Version                   Build  Channel
ca-certificates           2023.05.30           hca03da5_0  
libcxx                    14.0.6               h848a8c0_0  
libffi                    3.4.4                hca03da5_0  
ncurses                   6.4                  h313beb8_0  
openssl                   3.0.9                h1a28f6b_0  
pip                       23.1.2           py38hca03da5_0  
python                    3.8.16               hb885b13_4  
readline                  8.2                  h1a28f6b_0  
setuptools                67.8.0           py38hca03da5_0  
sqlite                    3.41.2               h80987f9_0  
tk                        8.6.12               hb8d0fd4_0  
wheel                     0.38.4           py38hca03da5_0  
xz                        5.4.2                h80987f9_0  
zlib                      1.2.13               h5a0b063_0  

**Run log**
(pythonProject3) Austin@pc-203-1 pythonProject3 % conda create --name cellpose python=3.8
WARNING: A conda environment already exists at '/Users/Austin/miniconda3/envs/cellpose'
Remove existing environment (y/[n])? Y

Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.5.0

## Package Plan ##

  environment location: /Users/Austin/miniconda3/envs/cellpose

  added / updated specs:
    - python=3.8

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-arm64::ca-certificates-2023.05.30-hca03da5_0 
  libcxx             pkgs/main/osx-arm64::libcxx-14.0.6-h848a8c0_0 
  libffi             pkgs/main/osx-arm64::libffi-3.4.4-hca03da5_0 
  ncurses            pkgs/main/osx-arm64::ncurses-6.4-h313beb8_0 
  openssl            pkgs/main/osx-arm64::openssl-3.0.9-h1a28f6b_0 
  pip                pkgs/main/osx-arm64::pip-23.1.2-py38hca03da5_0 
  python             pkgs/main/osx-arm64::python-3.8.16-hb885b13_4 
  readline           pkgs/main/osx-arm64::readline-8.2-h1a28f6b_0 
  setuptools         pkgs/main/osx-arm64::setuptools-67.8.0-py38hca03da5_0 
  sqlite             pkgs/main/osx-arm64::sqlite-3.41.2-h80987f9_0 
  tk                 pkgs/main/osx-arm64::tk-8.6.12-hb8d0fd4_0 
  wheel              pkgs/main/osx-arm64::wheel-0.38.4-py38hca03da5_0 
  xz                 pkgs/main/osx-arm64::xz-5.4.2-h80987f9_0 
  zlib               pkgs/main/osx-arm64::zlib-1.2.13-h5a0b063_0 

Proceed ([y]/n)? y

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate cellpose
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(pythonProject3) Austin@pc-203-1 pythonProject3 % conda activate cellpose
(cellpose) Austin@pc-203-1 pythonProject3 % python -m pip install cellpose
Collecting cellpose
  Using cached cellpose-2.2.2-py3-none-any.whl (171 kB)
Collecting numpy>=1.20.0 (from cellpose)
  Using cached numpy-1.24.4-cp38-cp38-macosx_11_0_arm64.whl (13.8 MB)
Collecting scipy (from cellpose)
  Using cached scipy-1.10.1-cp38-cp38-macosx_12_0_arm64.whl (28.8 MB)
Requirement already satisfied: natsort in /Users/Austin/.local/lib/python3.8/site-packages (from cellpose) (8.4.0)
Collecting tifffile (from cellpose)
  Using cached tifffile-2023.4.12-py3-none-any.whl (219 kB)
Collecting tqdm (from cellpose)
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting numba>=0.53.0 (from cellpose)
  Using cached numba-0.57.1-cp38-cp38-macosx_11_0_arm64.whl (2.5 MB)
Collecting llvmlite (from cellpose)
  Using cached llvmlite-0.40.1-cp38-cp38-macosx_11_0_arm64.whl (28.1 MB)
Collecting torch>=1.6 (from cellpose)
  Using cached torch-2.0.1-cp38-none-macosx_11_0_arm64.whl (55.8 MB)
Collecting opencv-python-headless (from cellpose)
  Using cached opencv_python_headless-4.8.0.74-cp37-abi3-macosx_11_0_arm64.whl (33.1 MB)
Collecting fastremap (from cellpose)
  Using cached fastremap-1.13.5-cp38-cp38-macosx_11_0_universal2.whl (1.2 MB)
Collecting imagecodecs (from cellpose)
  Using cached imagecodecs-2023.3.16.tar.gz (22.5 MB)
  Preparing metadata (setup.py) ... done
Collecting roifile (from cellpose)
  Using cached roifile-2023.5.12-py3-none-any.whl (15 kB)
Requirement already satisfied: importlib-metadata in /Users/Austin/.local/lib/python3.8/site-packages (from numba>=0.53.0->cellpose) (6.7.0)
Requirement already satisfied: filelock in /Users/Austin/.local/lib/python3.8/site-packages (from torch>=1.6->cellpose) (3.12.2)
Requirement already satisfied: typing-extensions in /Users/Austin/.local/lib/python3.8/site-packages (from torch>=1.6->cellpose) (4.7.1)
Collecting sympy (from torch>=1.6->cellpose)
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting networkx (from torch>=1.6->cellpose)
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Requirement already satisfied: jinja2 in /Users/Austin/.local/lib/python3.8/site-packages (from torch>=1.6->cellpose) (3.1.2)
Requirement already satisfied: zipp>=0.5 in /Users/Austin/.local/lib/python3.8/site-packages (from importlib-metadata->numba>=0.53.0->cellpose) (3.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/Austin/.local/lib/python3.8/site-packages (from jinja2->torch>=1.6->cellpose) (2.1.3)
Collecting mpmath>=0.19 (from sympy->torch>=1.6->cellpose)
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Building wheels for collected packages: imagecodecs
  Building wheel for imagecodecs (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      /Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/fb/d555n2lx06q5q7rl_240s18h0000gp/T/pip-install-a7a9n7b2/imagecodecs_7c66c728af0047ad94146696e62bc039/setup.py", line 680, in <module>
          setup(
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/dist.py", line 917, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/pkg_resources/__init__.py", line 827, in resolve
          dist = self._resolve_dist(
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1145, in obtain
          return installer(requirement)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/wheel.py", line 117, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/wheel.py", line 125, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/wheel.py", line 171, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/fb/d555n2lx06q5q7rl_240s18h0000gp/T/pip-install-a7a9n7b2/imagecodecs_7c66c728af0047ad94146696e62bc039/.eggs/numpy-1.24.4-py3.8-macosx-11.1-arm64.egg/numpy-1.24.4.dist-info' -> '/private/var/folders/fb/d555n2lx06q5q7rl_240s18h0000gp/T/pip-install-a7a9n7b2/imagecodecs_7c66c728af0047ad94146696e62bc039/.eggs/numpy-1.24.4-py3.8-macosx-11.1-arm64.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for imagecodecs
  Running setup.py clean for imagecodecs
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      /Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/fb/d555n2lx06q5q7rl_240s18h0000gp/T/pip-install-a7a9n7b2/imagecodecs_7c66c728af0047ad94146696e62bc039/setup.py", line 680, in <module>
          setup(
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/dist.py", line 917, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/pkg_resources/__init__.py", line 827, in resolve
          dist = self._resolve_dist(
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1145, in obtain
          return installer(requirement)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/wheel.py", line 117, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/wheel.py", line 125, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/Austin/miniconda3/envs/cellpose/lib/python3.8/site-packages/setuptools/wheel.py", line 171, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/fb/d555n2lx06q5q7rl_240s18h0000gp/T/pip-install-a7a9n7b2/imagecodecs_7c66c728af0047ad94146696e62bc039/.eggs/numpy-1.24.4-py3.8-macosx-11.1-arm64.egg/numpy-1.24.4.dist-info' -> '/private/var/folders/fb/d555n2lx06q5q7rl_240s18h0000gp/T/pip-install-a7a9n7b2/imagecodecs_7c66c728af0047ad94146696e62bc039/.eggs/numpy-1.24.4-py3.8-macosx-11.1-arm64.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for imagecodecs
Failed to build imagecodecs
ERROR: Could not build wheels for imagecodecs, which is required to install pyproject.toml-based projects

**Comment by Nickanda** [comment]
Found this in imagcodecs' README which is likely why you're having this issue:

`Python <= 3.8 is no longer supported. 32-bit versions are deprecated.`

I bumped my Python version up to 3.9 when initializing the conda environment and that solved this bug for me.

**Comment by TAspert** [comment]
> Found this in imagcodecs' README which is likely why you're having this issue:
> 
> `Python <= 3.8 is no longer supported. 32-bit versions are deprecated.`
> 
> I bumped my Python version up to 3.9 when initializing the conda environment and that solved this bug for me.

Worked for me, thanks!

**Comment by mrariden** [comment]
Resolved !

**Comment by apal6** [comment]
Hi,

I just loaded the python 3.8 version and still not able to install cellpose. Still the same error: 
`[end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for imagecodecs
Failed to build imagecodecs
ERROR: Could not build wheels for imagecodecs, which is required to install pyproject.toml-based projects
`
Any suggestions? 

Thank you in advance!

**Comment by bug1303** [comment]
As imagecodecs now requires python >= 3.9, you will either have to:

create your environment with `conda create --name cellpose python=3.9`

OR if for some reason you want to use python 3.8, install an older version of imagecodecs.
The last version that is supported by 3.8 was: https://pypi.org/project/imagecodecs/2023.3.16/
You can use  `conda install conda-forge::imagecodecs` from your environment and it will install a version that works for python 3.8.
