### ISSUE TITLE
[INSTALL] Mac M2: Cellpose ony lanches the first time after installation

### ISSUE THREAD

**Issue by przplz** [MouseLand/cellpose#801]
**Install problem**
Dear all,
I have installed cellpose 2.0 on my MAC M2 Pro and I ran into a problem. After installing it, I launched it and it worked fine, then I closed it and the following day I wanted to use it again. This error came out:

2023-10-06 11:49:16,291 [INFO] TORCH CUDA version not installed/working.
QPaintDevice: Cannot destroy paint device that is being painted
zsh: segmentation fault  python -m cellpose

I have tried creating a new cellpose virtual environment and re-installing it and the same issue occurred.

**Environment info**
# Name                    Version                   Build  Channel
ca-certificates           2023.08.22           hca03da5_0  
cachetools                5.3.1                    pypi_0    pypi
cellpose                  2.2.3                    pypi_0    pypi
certifi                   2023.7.22                pypi_0    pypi
charset-normalizer        3.3.0                    pypi_0    pypi
fastremap                 1.14.0                   pypi_0    pypi
filelock                  3.12.4                   pypi_0    pypi
fsspec                    2023.9.2                 pypi_0    pypi
google-api-core           2.12.0                   pypi_0    pypi
google-auth               2.23.2                   pypi_0    pypi
google-cloud-core         2.3.3                    pypi_0    pypi
google-cloud-storage      2.11.0                   pypi_0    pypi
google-crc32c             1.5.0                    pypi_0    pypi
google-resumable-media    2.6.0                    pypi_0    pypi
googleapis-common-protos  1.60.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imagecodecs               2023.9.18                pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
libcxx                    14.0.6               h848a8c0_0  
libffi                    3.4.4                hca03da5_0  
llvmlite                  0.41.0                   pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
natsort                   8.4.0                    pypi_0    pypi
ncurses                   6.4                  h313beb8_0  
networkx                  3.1                      pypi_0    pypi
numba                     0.58.0                   pypi_0    pypi
numpy                     1.25.2                   pypi_0    pypi
opencv-python-headless    4.8.1.78                 pypi_0    pypi
openssl                   3.0.11               h1a28f6b_2  
packaging                 23.2                     pypi_0    pypi
pip                       23.2.1           py39hca03da5_0  
protobuf                  4.24.4                   pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pygments                  2.16.1                   pypi_0    pypi
pyqt6                     6.5.2                    pypi_0    pypi
pyqt6-qt6                 6.5.2                    pypi_0    pypi
pyqt6-sip                 13.5.2                   pypi_0    pypi
pyqtgraph                 0.13.3                   pypi_0    pypi
python                    3.9.18               hb885b13_0  
qtpy                      2.4.0                    pypi_0    pypi
readline                  8.2                  h1a28f6b_0  
requests                  2.31.0                   pypi_0    pypi
roifile                   2023.8.30                pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scipy                     1.11.3                   pypi_0    pypi
setuptools                68.0.0           py39hca03da5_0  
sqlite                    3.41.2               h80987f9_0  
superqt                   0.6.0                    pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tifffile                  2023.9.26                pypi_0    pypi
tk                        8.6.12               hb8d0fd4_0  
torch                     2.1.0                    pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0  
urllib3                   2.0.6                    pypi_0    pypi
wheel                     0.41.2           py39hca03da5_0  
xz                        5.4.2                h80987f9_0  
zlib                      1.2.13               h5a0b063_0  
s.

**Run log**
(cellpose2) nerli@mateus-mac-5 ~ % python -m cellpose
2023-10-06 11:54:10,531 [INFO] WRITING LOG OUTPUT TO /Users/nerli/.cellpose/run.log
2023-10-06 11:54:10,531 [INFO] 
cellpose version: 	2.2.3 
platform:       	darwin 
python version: 	3.9.18 
torch version:  	2.1.0
2023-10-06 11:54:10,714 [INFO] TORCH CUDA version not installed/working.
QPaintDevice: Cannot destroy paint device that is being painted
zsh: segmentation fault  python -m cellpose
(cellpose2) nerli@mateus-mac-5 ~ %

**Comment by carsen-stringer** [comment]
I think this should be working now, will reopen if not

**Comment by przplz** [comment]
Hi Carsen, could you re-open this issue? It has happened again (haven't been using cellpose since august 2024) and I am still not sure how to fix it.
