### ISSUE TITLE
CellposeGUI Stuck on Draw Masks [BUG]

### ISSUE THREAD

**Issue by mayishazn** [MouseLand/cellpose#930]
**Describe the bug**
I have reinstalled cellpose 2. When I try to draw masks I right click and I see the red circle. I draw the mask and finish at the circle. The circle then disappears but no new mask appears. Instead the purple dots that indicate you are actively drawing an outline still appear. I noticed after returning to the red circle and the circle disappears, any additional movement of the cursor prints "QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)"

**To Reproduce**
1. right click to start drawing a mask
2. move mouse around a cell and return to red circle

**Run log**
(cellpose2) C:\Users\mayis>cellpose --verbose
2024-05-02 02:17:15,805 [INFO] WRITING LOG OUTPUT TO C:\Users\mayis\.cellpose\run.log
2024-05-02 02:17:16,473 [INFO] TORCH CUDA version not installed/working.
(2048, 2048, 4)
GUI_INFO: auto-adjust enabled, computing saturation levels
GUI_INFO: loaded in previous changes
GUI_INFO: 402 masks found in C:/Users/mayis/Downloads/C3-20x_MII_-_dapi_betacat-488_p120-568_ph633-02-0001_seg.npy
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)
QGraphicsScene::removeItem: item 0x1d8259b8340's scene (0x0) is different from this scene (0x1d827c093d0)

For the environment info: 
[env2.txt](https://github.com/MouseLand/cellpose/files/15184994/env2.txt)

**Comment by laurend** [comment]
I also have this bug!

**Comment by carsen-stringer** [comment]
Sorry, please upgrade, this is fixed in cellpose3

**Comment by mayishazn** [comment]
Also it seems this still sometimes but thankfully not always happens on cellpose3. Or like I'll draw the mask and it doesnt show up.

**Comment by mayishazn** [comment]
Ya this still happens on cellpose3

![image](https://github.com/MouseLand/cellpose/assets/43865608/7115bb8a-550e-4406-a073-79104aad2419)

**Comment by mayishazn** [comment]
![image](https://github.com/MouseLand/cellpose/assets/43865608/36402d26-6bcd-4c88-ad50-3a3abc43e1aa)

**Comment by mayishazn** [comment]
So what seems to work but isn't great is I reinstalled cellpose 1, went in the source code and swapped all the instances of np.bool to bool and np.float to float, and now I can finally draw masks. The workflow is now segment things with the python notebook with cellpose 3, fix the masks in cellpose 1, export them in cellpose 3... 

For what its worth I can sometimes get cellpose3 to draw exactly one mask before it gets stuck in draw mode, save, close cellpose, reopen cellpose3 and draw another mask but thats tedious as heck. I suppose one could compare the gui parts of both source codes and see where cellpose 3 gets stuck on draw mode but I'm not too confident if I'll be able to fix it that way.

**Comment by Anto9393** [comment]
I have exactly the same problem

**Comment by mayishazn** [comment]
> someone have any solution???

So what seems to work but isn't great is I reinstalled cellpose 1 (pip install cellpose==1.*), went in the source code and swapped all the instances of np.bool to bool and np.float to float, and now I can finally draw masks. The workflow is now segment things with the python notebook with cellpose 3, fix the masks in cellpose 1, export them in cellpose 3...

**Comment by carsen-stringer** [comment]
sorry I haven't been able to replicate this in windows, mac and linux with python=3.10 and python=3.11, please try upgrading, there are some suggestions in #961 , that issue will remain open until this is resolved

**Comment by mayishazn** [comment]
Hello! Sorry to bring this up again. I have tried the following steps.

run:
pip install pyqt6 --upgrade 
pip install pyqtgraph --upgrade
pip install cellpose --upgrade

I am not stuck in draw mode but the purple dotted lines linger and never turn into masks:
![image](https://github.com/user-attachments/assets/00377433-0bfa-4515-8daa-9932c8cce208)


I am using Windows 11. I am attaching the conda list and pip list 
[piplist_cellpose3.txt](https://github.com/user-attachments/files/17515460/piplist_cellpose3.txt)
[condalist_cellpose3.txt](https://github.com/user-attachments/files/17515461/condalist_cellpose3.txt)

Any help appreciated. I really like that cellpose 3 has a --Zstack option and it seems to stitch together the zstack quite well. Currently I'm still segmenting stuff in cellpose 3, saving them as individual slices via jupyter notebook, then reloading them on cellpose 1 to edit them. It would be nice to just use cellpose 3

**Comment by carsen-stringer** [comment]
Sorry this still isn't working, can you please try making a python=3.10 env? If that doesn't work I'll try to replicate your environment, please use this command and upload the yml: `conda env export > environment.yml`
